server:
  port: 8666
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/referal_links
    username: referal_links
    password: referal_links
  jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    host: ${app.mail.host}
    port: ${app.mail.port}
    username: ${app.mail.username}
    password: ${app.mail.password}

app:
  dictionary:
    countries:
      - Россия
      - Украина
      - Беларусь
      - Молдова
      - Белорусия
      - США
      - Великобритания
      - Германия
      - Франция
      - Новегия
      - Шведция
      - Другое
  mail:
    host: smtp.mail.ru
    port: 587
    username: nakombarov@mail.ru
    password: 5fbhD1Y5mVkBLFMU9Sfp